language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
